export {default as FeedIcon} from './feed.svg'
export {default as SearchIcon} from './search.svg'
export {default as BookmarkIcon} from './bookmark.svg'
export {default as ProfileIcon} from './profile.svg'
export {default as LogoIcon} from './logo.svg'
export {default as RecentIcon} from './recent.svg'